Add initial code
Draegerwerk/pysdccc pull request #1
Opened 2024-11-15 09:13 UTC by leon1995

2025-04-02 09:09 UTC, ldeichmann commented on src/pysdccc/_cli.py
> +        total = int(response.headers['Content-Length'])
If the transport is using http/1.1 and the transfer-encoding is chunked, there is no content-length - case needs to be handled

2025-04-02 09:25 UTC, ldeichmann commented on src/pysdccc/_cli.py
> +def _download_to_stream(
Why doesn't this use the download_to_stream function defined in _download? It seems like this should only exist once and progress can be controlled via a callback.

2025-04-24 11:27 UTC, pstaeck commented on .pre-commit-config.yaml
> +      - id: ruff-format
Did I understand it correctly that the source code is automatically changed here? To what extent does this happen and is this the desired behavior?

2025-04-24 11:43 UTC, leon1995 commented on src/pysdccc/_cli.py
> +        total = int(response.headers['Content-Length'])
made it optional

2025-04-24 11:46 UTC, leon1995 commented on .pre-commit-config.yaml
> +      - id: ruff-format
not sure what do you mean by `to what extent`, but it is desired to change the code, if you run tox in order not have to manually fix all the stuff that `ruff` is able to fix automatically

2025-04-24 11:49 UTC, pstaeck commented on .gitignore
> +src/pysdccc/_sdccc/
Pls. add a comment why this folder is ignored by git

2025-04-24 11:50 UTC, pstaeck commented on .gitignore
> +src/pysdccc/_sdccc/
I guess this file is from https://github.com/github/gitignore/blob/main/Python.gitignore?

Why did you remove 

# Ruff stuff:
.ruff_cache/

# PyPI configuration file
.pypirc

2025-04-24 11:59 UTC, pstaeck commented on .pre-commit-config.yaml
> +      - id: ruff-format
Ok, may it happen that the source code is changed automatically in the CI if a new build is triggered?

2025-04-24 12:41 UTC, pstaeck commented on uv.lock
> +]
Is there an issue if Python 3.13 is used since marker = "python_full_version < '3.13'"´for the dependency "typing-extension"

2025-04-24 12:58 UTC, leon1995 commented on .gitignore
> +src/pysdccc/_sdccc/
this file has been generated by `uv` I guess. I guess these files/directories arent used anymore

2025-04-24 12:59 UTC, leon1995 commented on uv.lock
> +]
tox executes unittest under python 3.13. I guess it works

2025-04-28 06:35 UTC, leon1995 commented on src/pysdccc/_cli.py
> +def _download_to_stream(
I reduced amount of code duplication

2025-04-28 06:36 UTC, leon1995 commented on .pre-commit-config.yaml
> +      - id: ruff-format
No, if a new ci pipleine is triggered, then it will checkout the code again and it will run into the same error

2025-04-28 06:37 UTC, leon1995 commented on .gitignore
> +src/pysdccc/_sdccc/
done

2025-05-05 08:52 UTC, pstaeck requested changes

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +        return_code, direct_result, invariant_result = runner.run(  # https://github.com/Draegerwerk/SDCcc/?tab=readme-ov-file#exit-codes
put the comment to the next line pls.

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +This python packages provides a convenient way to execute the [sdccc test suite](https://github.com/Draegerwerk/sdccc/).
please write SDCcc instead of sdccc, fix all occurrences.

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +For this open source project the [Contributor License Agreement](Contributor_License_Agreement.md) governs all relevant activities and your contributions. By contributing to the project you agree to
i am not sure, but i think we should use the lowercase letter here: ... bound to this **a**greement and ...

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +### Basic usage
I know this is the basic usage but short description and a doc string for both main functions would be very helpful.

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +Check out `pysdccc.download` or `pysdccc.download_async`. Otherwise, if `pysdccc[cli]` is installed, `$ pysdccc install https://url/to/sdccc.zip` can also be used.
I guess what is meant with pysdccc[cli] but someone else might not. Please explain this, or provide a link.

Maybe like this: "If the command line interface of pysdcc is installed, the zipped source of SDCcc can be installed using this command: `$ pysdccc install https://url/to/sdccc.zip`"

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +requirements = {
as a user I immediately ask myself whether the reqirements dictionary can be extended by adding other keys for other core standards. Maybe rxpand your example

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +config = {
is this the same config dictionary as mentioned in the "Create configuration file" section?, maybe rename it to "testparameter_config" or sth. like that?

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +    testparam=requirements_path,
this seems misleading to me, requirements and testsparam are pointing to a kind of requirements path.

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +requirements = runner.get_test_parameter()  # load default configuration
requirements is misleading here. It is easy to confuse it with the core requirements that should be tested. Maybe change to test_parameters?

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +```
Overall, there are three steps the user has to think of. Basic configuration, which requiremtents/tests and if there are test specific parameters. May it is a better aproach to give one code example that combines every thing supported by proper comments?

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +### Execute sdccc from cli
pls. change to: Execute SDCcc from command-line interface (CLI)

2025-05-05 08:52 UTC, pstaeck commented on README.md
> +There exists a cli wrapper for the sdccc executable. If `pysdccc[cli]` is installed, `$ sdccc` can be used to execute arbitrary sdccc commands, e.g. `sdccc --version`. More information can be found [
add a "$" to the example command

2025-05-05 09:46 UTC, pstaeck requested changes

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/__init__.py
> +"""Python wrapper to the sdccc tool for testing SDC devices."""
SDCcc

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
> +    msg = "Cli not installed. Please install using 'pip install pysdccc[cli]."
missing word: Please install **it** using ...

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
> +        except Exception as e:  # noqa: BLE001
what is this comment for?

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
> +            self.fail(f'{value!r} is not a valid proxy: {e}', param, ctx)
my linter complains that "Either all return statements in a function should return an expression, or none of them should."
pls. add a raise

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
> +            self.fail(f'{value!r} is not a valid url: {e}', param, ctx)
add raise?!

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
pls. add a module, class, function and method docstrings

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
optional: i would prefer writing the error message directly into the error object instead of reassigning "msg" every time.

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
> +        except Exception as e:  # noqa: BLE001
ok, i get it, blind except for your linter

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
> +        click.ClickException("sdccc is not installed. Please install using 'pysdccc install <url>'.").show()
SDCcc

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
pls. write SDCcc where necessary

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_common.py
please add a module docstring

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_download.py
pls. add module and function docstrings
write SDCcc where necessary

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_cli.py
> +    short_help='Install the SDCcc executable from the specified URL. Releases can be found at https://github.com/Draegerwerk/SDCcc/releases.',
line too long?!

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_runner.py
> +            return_code = subprocess.run(command, timeout=timeout, check=True, cwd=self.exe.parent).returncode  # noqa: S603
line too long

2025-05-05 09:46 UTC, pstaeck commented on src/pysdccc/_runner.py
> +        process = subprocess.run([str(self.exe), '--version'], check=True, capture_output=True, cwd=self.exe.parent)  # noqa: S603
line too long

2025-05-05 12:01 UTC, pstaeck requested changes

2025-05-07 13:17 UTC, pstaeck requested changes

2025-05-08 12:38 UTC, pstaeck requested changes

2025-05-08 12:38 UTC, pstaeck commented on tests/test_runner.py
> +def test_load_configuration():
what about a complexer example than just a one liner :)
You can even do this:

    def test_load_configuration():
    """Test that the configuration is correctly loaded from a TOML file."""
    example_toml = pathlib.Path('testversion/configuration/config.toml')
    assert (_load_configuration(example_toml) ==
            {'SDCcc': {'CIMode': False,
                       'Consumer': {
                           'DeviceEpr': 'urn:uuid:857bf583-8a51-475f-a77f-d0ca7de69b11',
                           'Enable': True},
                       'EnableMessageEncodingCheck': True,
                       'GraphicalPopups': True,
                       'Network': {'InterfaceAddress': '127.0.0.1',
                                   'MaxWait': 10,
                                   'MulticastTTL': 128},
                       'Provider': {'Enable': False},
                       'SummarizeMessageEncodingErrors': True,
                       'TLS': {'EnabledCiphers': [
                           'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256',
                           'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
                           'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384',
                           'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384',
                           'TLS_DHE_RSA_WITH_AES_128_GCM_SHA256',
                           'TLS_DHE_RSA_WITH_AES_256_GCM_SHA384',
                           'TLS_AES_128_GCM_SHA256',
                           'TLS_AES_256_GCM_SHA384'],
                           'EnabledProtocols': ['TLSv1.2', 'TLSv1.3'],
                           'FileDirectory': './configuration',
                           'KeyStorePassword': 'whatever',
                           'ParticipantPrivatePassword': 'dummypass',
                           'TrustStorePassword': 'whatever'},
                       'TestExecutionLogging': True,
                       'TestParameter': {'Biceps547TimeInterval': 5},
                       'gRPC': {'ServerAddress': 'localhost:50051'}
                       }
             }
            )

2025-05-08 12:53 UTC, pstaeck commented on tests/test_common.py
> +    key1 = uuid.uuid4().hex
This are the values and not the keys, arent they?

2025-05-09 06:03 UTC, leon1995 commented on README.md
> +This wrapper is only compatible with sdccc versions later than [ebe0e09](https://github.com/Draegerwerk/SDCcc/commit/ebe0e094ff92649d0bda1988b0d1c1b08403aea4).
by the time writing there was no release available. and even now, there is only a pre release, but I will reference that

2025-05-09 06:04 UTC, leon1995 commented on README.md
> +
done

2025-05-09 06:06 UTC, leon1995 commented on README.md
> +This python packages provides a convenient way to execute the [sdccc test suite](https://github.com/Draegerwerk/sdccc/).
done

2025-05-09 06:11 UTC, leon1995 commented on README.md
> +        return_code, direct_result, invariant_result = runner.run(  # https://github.com/Draegerwerk/SDCcc/?tab=readme-ov-file#exit-codes
done

2025-05-09 06:19 UTC, leon1995 commented on README.md
> +### Basic usage
renamed to `Quick start`

2025-05-09 06:29 UTC, leon1995 commented on README.md
> +Check out `pysdccc.download` or `pysdccc.download_async`. Otherwise, if `pysdccc[cli]` is installed, `$ pysdccc install https://url/to/sdccc.zip` can also be used.
done

2025-05-09 06:31 UTC, leon1995 commented on README.md
> +requirements = {
ofc it can be extended, if SDCcc supports it. There is also a link to the tests supported by sdccc. I added a comment to explain what the key and what the value is

2025-05-09 06:37 UTC, leon1995 commented on README.md
> +    testparam=requirements_path,
good catch. fixed

2025-05-09 06:38 UTC, leon1995 commented on README.md
> +requirements = runner.get_test_parameter()  # load default configuration
done

2025-05-09 06:42 UTC, leon1995 commented on README.md
> +### Execute sdccc from cli
done

2025-05-09 06:43 UTC, leon1995 commented on src/pysdccc/__init__.py
> +"""Python wrapper to the sdccc tool for testing SDC devices."""
done

2025-05-09 06:44 UTC, leon1995 commented on src/pysdccc/_cli.py
> +    msg = "Cli not installed. Please install using 'pip install pysdccc[cli]."
done

2025-05-09 06:49 UTC, leon1995 commented on src/pysdccc/_cli.py
> +            self.fail(f'{value!r} is not a valid proxy: {e}', param, ctx)
if I add a `return None` here, my IDE complains that this code is unreachable, because `self.fail(...)` raises an exception itself

2025-05-09 06:49 UTC, leon1995 commented on src/pysdccc/_cli.py
> +            self.fail(f'{value!r} is not a valid url: {e}', param, ctx)
return would be unreachable

2025-05-09 06:52 UTC, leon1995 commented on src/pysdccc/_cli.py
ruff would complain, checkout the error messages

2025-05-09 06:52 UTC, leon1995 commented on src/pysdccc/_cli.py
> +        click.ClickException("sdccc is not installed. Please install using 'pysdccc install <url>'.").show()
done

2025-05-09 06:56 UTC, leon1995 commented on src/pysdccc/_cli.py
done

2025-05-09 06:56 UTC, leon1995 commented on src/pysdccc/_cli.py
> +    short_help='Install the SDCcc executable from the specified URL. Releases can be found at https://github.com/Draegerwerk/SDCcc/releases.',
if ruff is not complaining, its not too long :D

2025-05-09 06:57 UTC, leon1995 commented on src/pysdccc/_runner.py
> +            return_code = subprocess.run(command, timeout=timeout, check=True, cwd=self.exe.parent).returncode  # noqa: S603
if ruff is not complaining, its not too long :D

2025-05-09 06:57 UTC, leon1995 commented on src/pysdccc/_runner.py
> +        process = subprocess.run([str(self.exe), '--version'], check=True, capture_output=True, cwd=self.exe.parent)  # noqa: S603
if ruff is not complaining, its not too long :D

2025-05-09 06:57 UTC, leon1995 commented on tests/test_download.py
> +import io
done

2025-05-09 06:57 UTC, leon1995 commented on tests/test_download.py
> +from collections.abc import AsyncIterator
done

2025-05-09 06:58 UTC, leon1995 commented on tests/test_download.py
> +    assert not (await ais_downloaded(uuid.uuid4().hex))
done

2025-05-09 06:59 UTC, leon1995 commented on tests/result/TEST-SDCcc_direct.xml
done

2025-05-09 07:01 UTC, leon1995 commented on tests/sdccc_result.xml
done

2025-05-09 07:01 UTC, leon1995 commented on tests/test_result_parser.py
> +    element._elem = mock.Mock()  # noqa: SLF001
I dont really want to generally disable it for the whole file

2025-05-09 07:20 UTC, leon1995 commented on README.md
> +For this open source project the [Contributor License Agreement](Contributor_License_Agreement.md) governs all relevant activities and your contributions. By contributing to the project you agree to
legal stuff...

2025-05-09 07:42 UTC, pstaeck commented on src/pysdccc/_download.py
> +    output = output or _runner.DEFAULT_STORAGE_DIRECTORY
you are right

2025-05-09 07:49 UTC, pstaeck commented on tests/test_result_parser.py
> +    element._elem = mock.Mock()  # noqa: SLF001
ok for me

2025-05-09 09:58 UTC, leon1995 commented on README.md
> +There exists a cli wrapper for the sdccc executable. If `pysdccc[cli]` is installed, `$ sdccc` can be used to execute arbitrary sdccc commands, e.g. `sdccc --version`. More information can be found [
remove `$`

2025-05-09 10:11 UTC, leon1995 commented on src/pysdccc/_cli.py
done

2025-05-09 10:14 UTC, leon1995 commented on src/pysdccc/_common.py
done

2025-05-09 10:22 UTC, leon1995 commented on src/pysdccc/_download.py
done

2025-05-09 10:24 UTC, leon1995 commented on src/pysdccc/_download.py
> +    """Download the specified version from the URL.
done

2025-05-09 10:25 UTC, leon1995 commented on src/pysdccc/_download.py
> +    """
done

2025-05-09 10:25 UTC, leon1995 commented on src/pysdccc/_download.py
> +    output = output or _runner.DEFAULT_STORAGE_DIRECTORY
no, see above for reason

2025-05-09 10:31 UTC, leon1995 commented on tests/test_runner.py
> +    assert not pathlib.Path('sdccc-1.0.0.exe').exists()
done

2025-05-09 11:08 UTC, leon1995 commented on tests/test_common.py
> +    key1 = uuid.uuid4().hex
done

2025-05-09 12:57 UTC, pstaeck commented on src/pysdccc/_cli.py
> +            self.fail(f'{value!r} is not a valid proxy: {e}', param, ctx)
As discussed, it is the task of the user to keep this in mind. Check if the implementation of fail is as expected in the used version of click. The risk is low.

2025-05-09 12:57 UTC, pstaeck commented on src/pysdccc/_cli.py
> +            self.fail(f'{value!r} is not a valid url: {e}', param, ctx)
As discussed, it is the task of the user to keep this in mind. Check if the implementation of fail is as expected in the used version of click. The risk is low.

2025-05-09 13:43 UTC, pstaeck commented on README.md
> +```
after discussion and adapting the variable names the three step example approach is ok

2025-05-12 12:16 UTC, pstaeck commented on src/pysdccc/_runner.py
> +        command = self._prepare_command(config=pathlib.Path(config), requirements=pathlib.Path(requirements), **kwargs)
1. If i get it right the path to the executable is missing

2. I have no log messages on my console when running the async example. Maybe i am doing sth. wrong. Other wise a solution may reading out stdout and log this?! On the other hand, the log messages are written to the SDCcc.log.

2025-05-13 09:59 UTC, pstaeck commented on src/pysdccc/_cli.py
> +        total = int(response.headers['Content-Length'])
@ldeichmann ask me to take over, solved for me

2025-05-13 11:00 UTC, pstaeck commented on src/pysdccc/_cli.py
> +def _download_to_stream(
@ldeichmann ask me to take over, solved for me

2025-05-14 07:14 UTC, pstaeck commented on README.md
> +This python packages provides a convenient way to execute the [sdccc test suite](https://github.com/Draegerwerk/sdccc/).
There are still some occurrences of sdccc that could be changed to SDCcc

2025-05-14 07:20 UTC, pstaeck commented on README.md
> +requirements = runner.get_test_parameter()  # load default configuration
pls. check again.

config and requirements are pointing to the same ".../file.toml" and testparam should point to the test parameter toml and not to the testparameter_config dict

2025-05-14 07:30 UTC, pstaeck commented on tests/test_download.py
> +    """Test that the download function correctly downloads and extracts the executable."""
can stay as it is

2025-05-14 07:54 UTC, pstaeck commented on tests/test_runner.py
> +def test_load_configuration():
removed as discussed

2025-05-14 07:54 UTC, pstaeck commented on src/pysdccc/_runner.py
> +        command = self._prepare_command(config=pathlib.Path(config), requirements=pathlib.Path(requirements), **kwargs)
fixed as discussed

2025-05-15 13:05 UTC, merged